name: CI

on:
  push:
    tags:        
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Notify release
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_KEY }}
        EVENT_DESCRIPTION: ${{ toJson(github) }}
      run: |
        curl -X POST -H 'Authorization: ${{ secrets.SLACK_BOT_KEY }}' -H 'Content-type: application/json;charset=utf-8' --data '{"channel":"#testplugins","text":"La librería `${{ github.event.repository.name }}` acaba de subir su versión a `${{ github.ref_name }}`"}' https://slack.com/api/chat.postMessage
